# -*- coding: utf-8 -*-
# vim: ft=yaml
---
kubernetes:
  div: '/'
  clean: false
  overwrite: true   # for archive.extracted on windows
  formula: kubernetes
  supported:
    - server
    - client
    - node
    - k3s
    - operator
    - operators
    - devlibs
    - devtools
    - sigs
    - crimgr
  sigs:
    wanted:
      - kind
      - krew
      - kubebuilder
    pkg:
      kind:
        version: 0.11.1
        commands:
          - kind
        use_upstream: binary
        uri_b: 'https://github.com/kubernetes-sigs/kind/releases/download'
        uri_d: 'https://github.com/kubernetes-sigs/kind/tree/master/images'   # docker images
        binary:
          source_hash: '949f81b3c30ca03a3d4effdecda04f100fa3edc07a28b19400f72ede7c5f0491'  # noqa 204
      krew:
        version: 0.4.1
        commands:
          - krew-linux_amd64
        use_upstream: archive
        uri_a: 'https://github.com/kubernetes-sigs/krew/releases/download'
        archive:
          options: '--strip-components=1'
        suffix: tar.gz
      kubebuilder:
        version: 3.1.0
        commands:
          # etcd
          # kube-apiserver
          - kubebuilder
          # kubectl
        use_upstream: binary
        uri_a: 'https://github.com/kubernetes-sigs/kubebuilder/releases/download'
        binary:
          source_hash: 'a4af6a2110cf506855cdc86d0291c6e76203ae9fb3c918f7fdc05e7962e4b488'  # noqa 204

  devtools:
    wanted:
      - audit2rbac
      - cue
      - devspace
      - dive
      - istio
      - kubectx
      - kubens
      - kudo
      - linkerd2
      - minikube
      - octant
      - skaffold
      - stern
    pkg:
      devspace:
        version: 5.15.0
        commands:
          - devspace
        use_upstream: binary
        uri_b: 'https://github.com/devspace-cloud/devspace/releases/download'
        binary: {}  # needed
        suffix: null
        container:
          image: devspacesh/devspace
      octant:
        version: 0.23.0
        commands:
          - octant
        use_upstream: archive
        uri_a: 'https://github.com/vmware-tanzu/octant/releases/download'
        archive:  # 64bit
          source_hash: '91a49c4438b07def60078ebbd86469d96517832ee214b975c79a8c63350f39c9'  # noqa 204
          options: '--strip-components=1'
        suffix: tar.gz
      linkerd2:
        version: 21.9.1
        commands:
          - linkerd2
        use_upstream: binary
        uri_b: 'https://github.com/linkerd/linkerd2/releases/download'
        binary: {}  # needed
        suffix: ''
      skaffold:
        version: 1.31.0
        commands:
          - skaffold
        use_upstream: binary
        uri_b: 'https://storage.googleapis.com/skaffold/releases'
        binary: {}  # needed
        suffix: ''
        container:
          image: shahidh/skaffold
      istio:
        version: 1.11.2
        commands:
          - istioctl
        use_upstream: archive
        uri_a: 'https://github.com/istio/istio/releases/download'
        archive:
          options: '--strip-components=1'
        suffix: tar.gz
        container:
          image: istio/base   # ??
      dive:
        version: 0.10.0
        commands:
          - dive
        use_upstream: archive
        uri_a: 'https://github.com/wagoodman/dive/releases/download'
        archive:
          source_hash: '9541997876d4985de66d0fa5924dac72258a3094ef7d3f6ef5fa5dcf6f6a47ad'  # noqa 204
          options: '--strip-components=1'
        suffix: tar.gz
        container:
          image: wagoodman/dive
      kudo:
        version: 0.19.0
        name: kubectl-kudo
        commands:
          - kudo
        use_upstream: binary
        uri_b: 'https://github.com/kudobuilder/kudo/releases/download'
        binary:
          source_hash: '6a13d44cfe1afc8fd949f162f072142375f072783b94f4034e8d7b1efcd02bd9'  # noqa 204
        suffix: tar.gz
      minikube:
        version: 1.23.0
        commands:
          - minikube
        config_file: /etc/default/minikube.ini
        config: {}
        environ_file: /etc/default/minikube.sh
        environ: []
        service: {}
        vm_driver: none
        use_upstream: binary
        uri_b: 'https://github.com/kubernetes/minikube/releases/download'
        binary: {}  # needed
        suffix: null
      stern:
        version: 1.11.0
        commands:
          - stern
        use_upstream: binary
        uri_b: 'https://github.com/wercker/stern/releases/download'
        binary:
          source_hash: 'e0b39dc26f3a0c7596b2408e4fb8da533352b76aaffdc18c7ad28c833c9eb7db'  # noqa 204
        suffix: ''
        container:
          image: heriet/stern
      kubectx:
        version: 0.9.4
        commands:
          - kubectx
        use_upstream: archive
        uri_a: 'https://github.com/ahmetb/kubectx/releases/download'
        archive:
          source_hash: 'db5a48e85ff4d8c6fa947e3021e11ba4376f9588dd5fa779a80ed5c18287db22'  # noqa 204
          options: ''
        suffix: tar.gz
      kubens:
        version: 0.9.4
        commands:
          - kubens
        use_upstream: archive 
        uri_a: 'https://github.com/ahmetb/kubectx/releases/download'
        archive:
          source_hash: '8b3672961fb15f8b87d5793af8bd3c1cca52c016596fbf57c46ab4ef39265fcd'  # noqa 204
          options: ''
        suffix: tar.gz
      cue:
        version: v0.4.0
        commands:
          - cue
        use_upstream: archive
        uri_a: 'https://github.com/cuelang/cue/releases/download'
        archive:
          source_hash: 'a118177d9c605b4fc1a61c15a90fddf57a661136c868dbcaa9d2406c95897949'  # noqa 204
          options: ''
        suffix: tar.gz
        container:
          image: cuelang/cue
      audit2rbac:
        version: 0.8.0
        commands:
          - audit2rbac
        use_upstream: archive
        uri_a: 'https://github.com/liggitt/audit2rbac/releases/download'
        archive:
          source_hash: '7703cbf3c9c555ea91d4120acf106502fce64c6afdbe1c5aec603a4864560631'  # noqa 204
          options: '--strip-components=0'
        suffix: tar.gz

  devlibs:
    wanted:
      - java
      - python
      - csharp
      - javascript
      - kopf
      - k8s
    pkg:
      java:
        name: 'client-java-parent-'
        version: 13.0.0
        use_upstream: archive
        uri_a: 'https://github.com/kubernetes-client'
        archive:
          source_hash: '71107d0fc1e2530a767c8bd71e1f939af6cd4e412acc032289ff109bffba9867'  # noqa 204
          options: '--strip-components=1'
        suffix: tar.gz
      python:
        name: v
        version: 18.20.0
        use_upstream: archive
        uri_a: 'https://github.com/kubernetes-client'
        archive:
          source_hash: '5320cec65d9dab7baa28fe542847888d604fb02e511f0464d0e93a948ac071c8'  # noqa 204
          options: '--strip-components=1'
        suffix: tar.gz
      csharp:
        name: ''
        version: 1.2.0
        use_upstream: archive
        uri_a: 'https://github.com/kubernetes-client'
        archive:
          source_hash: '0edcefd17f50d0e9d5b34ea318a6a5a13cf9448f918ffa9dec519da9457f9159'
          options: '--strip-components=1'
        suffix: tar.gz
      javascript:
        name: ''
        version: 0.15.0
        use_upstream: archive
        uri_a: 'https://github.com/kubernetes-client'
        archive:
          source_hash: '06aa836c5f9d2704711af79736ae42283007320d0b00987b9a325cbe38728e83'
          options: '--strip-components=1'
        suffix: tar.gz
      kopf:
        name: ''
        version: 0.27
        use_upstream: archive
        uri_a: 'https://github.com/zalando-incubator/kopf/archive'
        archive:
          source_hash: '25a98ca73b3e7ea8bc38dc31cd5e3f2bd6d443490395166b61eeaeb02d9e1d4d'
          options: '--strip-components=1'
        suffix: tar.gz
      k8s:
        name: v
        version: 1.2.0
        use_upstream: archive
        uri_a: 'https://github.com/ericchiang/k8s/archive'
        archive:
          source_hash: '18f4c90d7b206d9abb69aff007a534e6cf2e723cbc7d4bb74cc32ec619c418ca'
          options: '--strip-components=1'
        suffix: tar.gz

  operator:
    sdk:
      # https://sdk.operatorframework.io
      rsakey: '0CF50BEE7E4DF6445E08C0EA9AFDE59E90D2B445'
      rsakeyserver: 'keyserver.ubuntu.com'
      wanted:
        - ansible-operator
        - helm-operator
        - operator-sdk
      pkg:
        ansible-operator:
          version: 1.11.0
          use_upstream: binary
          uri_b: 'https://github.com/operator-framework/operator-sdk/releases/download'
          binary:
            source_hash: '32c1291d32f6c0389f3331f4797a1e03be6797c85b3c471be5c588cb16b0261d'  # noqa 204
          commands:
            - ansible-operator
          container:
            image: alaypatel07/ansible-operator
        helm-operator:
          version: 1.11.0
          use_upstream: binary
          uri_b: 'https://github.com/operator-framework/operator-sdk/releases/download'
          binary:
            source_hash: 'fc951746e94796c8377f4dce499fd275aae4f59a364efde79e9101d64486d70d'  # noqa 204
          commands:
            - helm-operator
          container:
            image: fluxcd/helm-operator
        operator-sdk:
          version: 1.11.0
          use_upstream: binary
          uri_b: 'https://github.com/operator-framework/operator-sdk/releases/download'
          binary:
            source_hash: 'b1f6fb02c619cfcdb46edf41cbeb4d66f627fd8bba122edaeeb06718965299eb'  # noqa 204
          commands:
            - operator-sdk
          container:
            image: figaw/operator-sdk

  operators:
    # https://operatorhub.io
    wanted:
      - grafana-operator
      - prometheus-operator
      - akka-cluster-operator
      - istio-operator
      - shell-operator
    pkg:
      akka-cluster-operator:
        version: 1.0.3
        use_upstream: archive
        uri_a: 'https://github.com/lightbend/akka-cluster-operator/archive'
        archive:
          source_hash: 'c015898a4f580386b62003fc467df2aac3877206c02ea298bae0d0a3feba8186'  # noqa 204
          options: '--strip-components=1'
        suffix: tar.gz
        container:
          image: lightbend-docker-registry.bintray.io/lightbend/akkacluster-operator
      grafana-operator:
        version: 3.10.3
        use_upstream: archive
        uri_a: 'https://github.com/integr8ly/grafana-operator/archive'
        archive:
          source_hash: 'b12a2f3bce7e5f8192f59a6e12597e4ead5f3c536ae4646c8755142429212c3a'  # noqa 204
          options: '--strip-components=1'
        suffix: tar.gz
        container:
          image: grafana/grafana
      prometheus-operator:
        version: 0.50.0
        use_upstream: archive
        uri_a: 'https://github.com/coreos/prometheus-operator/archive'
        archive:
          source_hash: '4f5c7e251c07034a0916bdb1dc1cd76894d5810811bc977682c9831aeecaae63'  # noqa 204
          options: '--strip-components=1'
        suffix: tar.gz
        container:
          image: quay.io/coreos/prometheus-operator
      istio-operator:
        version: 0.10.6
        use_upstream: archive
        uri_a: 'https://github.com/banzaicloud/istio-operator/archive'
        archive:
          source_hash: '77e09fc27f9bf43da86c0d2383e35b175df04256e445e4e7e049ad3cb5cec50f'  # noqa 204
          options: '--strip-components=1'
        suffix: tar.gz
        container:
          image: banzaicloud/istio-operator
      shell-operator:
        version: 1.0.3
        use_upstream: archive
        uri_a: 'https://github.com/flant/shell-operator/archive'
        archive:
          source_hash: '44c1d8bcfdb4e4642bbd32702aac5ade67065abeac8ca7fe8b0561559291fcb1'  # noqa 204
          options: '--strip-components=1'
        suffix: tar.gz
        container:
          image: flant/shell-operator

  server:
    version: 1.22.1
    config_file: /etc/default/kubernetes-server.ini
    config: {}
    environ_file: /etc/default/kubernetes-server.sh
    environ: []
    service: {}
    pkg:
      name: kubernetes-server
      commands:
        - apiextensions-apiserver
        - kube-scheduler
        - kubeadm
        # kubectl
        - kubelet
        - mounter
        - kube-apiserver
        - kube-controller-manager
        - kube-proxy
      use_upstream: archive
      uri_a: 'https://dl.k8s.io'
      archive:
        options: '--strip-components=2'
        source_hash: '66c596577d19c1a609b554e1e61b0bc2c8ba691b2101f481dfc616799e37347edc62956b7684370dec5b16388d48a665ba78c942de4aaf5df1f78cf0667df545'  # noqa 204
      suffix: tar.gz

  client:
    version: 1.22.1
    aliases_file: /etc/default/kubernetes-aliases.sh
    pkg:
      name: kubectl
      commands:
        - kubectl
      use_upstream: archive
      uri_a: 'https://dl.k8s.io'
      uri_b: 'https://storage.googleapis.com/kubernetes-release/release'  # binary
      archive:
        options: '--strip-components=2'
        source_hash: '064bd1eaf468c9b4a00e31bec3f9c80850c52cd1e06edfd86f307236acbdba7c89dbe663cbfefdc5ead72f1cb93ba9d21d828558508f0b29f8c814d9085846ca' # noqa 204
      binary:
        name: kubernetes-client
        source_hash: ''
      suffix: tar.gz

  node:
    version: 1.22.1
    config_file: /etc/default/kubernetes-node.ini
    config: {}
    service: {}
    pkg:
      name: kubernetes-node
      commands: {}
        # kubeadm
        # kubectl
        # kubelet
        # kube-proxy
      use_upstream: archive
      uri_a: 'https://dl.k8s.io'
      archive:
        source_hash: '53b44fbf58308c18b478ced5629a82d01c67dd6ae5be9559a2d65edae339983bff4d143b1bde062f5d8202ec8241e45da3b087af1fb0aea35afb1812a26450d1'  # noqa 204
        options: '--strip-components=2'
      suffix: tar.gz

  crimgr:
    version: 0.5.0
    config_file: /etc/cri-resmgr/fallback.cfg
    config: {}
    environ: {}
    environ_file: /etc/default/cri-resource-manager
    service: {}
    pkg:
      use_upstream: archive
      uri_a: 'https://github.com/intel/cri-resource-manager/releases/download'
      archive:
        source_hash: '97e117989b3d515dac86cfb0e5c14a69406a29bc5a17b5d8f13e41234b630f0b'  # noqa 204
      suffix: tar.gz

  k3s:
    version: v1.21.4+k3s1   # include v in this version
    pkg:
      commands:
        - k3s
      use_upstream: binary
      uri_b: 'https://github.com/rancher/k3s/releases/download'
      uri_s: 'https://get.k3s.io'
      binary:
        source_hash: 'b7f8c026c5346b3e894d731f1dc2490cd7281687549f34c28a849f58c62e3e48'  # noqa 204
      script:
        source_hash:
        killall: /usr/local/bin/k3s-killall.sh
        uninstall: /usr/local/bin/k3s-uninstall.sh
        env:
          INSTALL_K3S_BIN_DIR: /usr/local/bin
          INSTALL_K3S_SELINUX_WARN: true
          # INSTALL_K3S_BIN_DIR_READ_ONLY: false
          # INSTALL_K3S_CHANNEL_URL: 'https://update.k3s.io/v1-release/channels'
          # INSTALL_K3S_CHANNEL: stable
          # INSTALL_K3S_EXEC: ''
          # INSTALL_K3S_NAME: ''
          # INSTALL_K3S_SKIP_DOWNLOAD: false
          # INSTALL_K3S_SYMLINK: skip
          # INSTALL_K3S_SKIP_ENABLE: false
          # INSTALL_K3S_SKIP_START: false
          # INSTALL_K3S_SYSTEMD_DIR: /etc/system/systemd
          # INSTALL_K3S_TYPE: ''
          # INSTALL_K3S_VERSION: ''
          # K3S_AGENT_TOKEN: ''
          # K3S_AGENT_TOKEN_FILE: ''
          # K3S_CLUSTER_INIT: ''
          # K3S_CLUSTER_RESET: ''
          # K3S_CLUSTER_SECRET: ''
          # K3S_DATASTORE_ENDPOINT: ''
          # K3S_DATASTORE_CAFILE: ''
          # K3S_DATASTORE_CERTFILE: ''
          # K3S_DATASTORE_KEYFILE:''
          # K3S_KUBECONFIG_MODE: ''
          # K3S_NODE_NAME: ''
          # K3S_RESOLV_CONF: ''
          # K3S_TOKEN: ''
          # K3S_TOKEN_FILE: ''
          # KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      suffix: tar.gz
      container:
        image: rancher/k3s

  identity:
    rootuser: root
    rootgroup: root
  arch: ''
  dir:
    base: /usr/local/
    source: /usr/local/src/k8s/libs/
    operators: /usr/local/src/k8s/operators/
    tmp: /tmp/kubernetes-tmp/
  pkg:
    deps:
      - curl
      - tar
      - gzip
    repo:
      humanname: kubernetes
      name: kubernetes
      comments:
        - installed by salt
      enabled: 1
      gpgcheck: 1
  linux:
    altpriority: 0

  retry_option:
    # https://docs.saltstack.com/en/latest/ref/states/requisites.html#retrying-states
    attempts: 3
    until: true
    interval: 60
    splay: 10

  # Just here for testing
  added_in_defaults: defaults_value
  winner: defaults
